# Jenkins-only override for docker-compose.yml.
services:
  serverhub:
    volumes:
      - serverhub-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  prometheus:
    volumes:
      - /var/snap/docker/common/var-lib-docker/volumes/jenkins_home/_data/workspace/server-hub-pipeline/server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/snap/docker/common/var-lib-docker/volumes/jenkins_home/_data/workspace/server-hub-pipeline/server/rules:/etc/prometheus/rules:ro
      - promdata:/prometheus

  alertmanager:
    volumes:
      - /var/snap/docker/common/var-lib-docker/volumes/jenkins_home/_data/workspace/server-hub-pipeline/server/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - amdata:/alertmanager

volumes:
  serverhub-data:
